version: '3'
volumes:
    nexus_data:
services:
    nginx:
        image: nginx:alpine
        container_name: springworks_nginx
        ports:
            - "80:80"
        volumes:
            - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
        links:
            - nexus
        depends_on:
            - nexus
    nexus:
        image: sonatype/nexus3:latest
        container_name: springworks_nexus
        environment:
            - NEXUS_CONTEXT=nexus
        volumes:
            - nexus_data:/nexus-data

